version: '3.7'

services:
  server:
    build:
      context: ./backend/auth-api
      dockerfile: Dockerfile
    image: medico-server
    container_name: medico-node-server
    command: npm run server
    ports:
      - "4000:4000"
      - "8000:8000"
    depends_on:
      - redisdb
    networks:
      - app-network

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: medico-client
    container_name: medico-node-client
    command: npm run start
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

  redisdb:
    image: 'redis:alpine'
    restart: always
    hostname: redisdb
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - app-network

networks:
    app-network:
        driver: bridge